In [1]:
# from pygbif import species as species
# from pygbif import occurrences as occ

import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
df_sw = pd.read_csv("data/gbif_nz_snow_wren.csv", sep='\t')
df_sw.head()

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,...,identifiedBy,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue
0,977205778,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS225716267,Animalia,Chordata,Aves,Passeriformes,Acanthisittidae,Xenicus,Xenicus gilviventris,...,NaN,NaN,CC_BY_4_0,NaN,obsr337627,NaN,NaN,2024-04-17T08:23:32.337Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...
1,976924999,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD_NZ:OBS224521212,Animalia,Chordata,Aves,Passeriformes,Acanthisittidae,Xenicus,Xenicus gilviventris,...,NaN,NaN,CC_BY_4_0,NaN,obsr444699,NaN,NaN,2024-04-17T09:07:24.802Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...
2,964538944,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS209872557,Animalia,Chordata,Aves,Passeriformes,Acanthisittidae,Xenicus,Xenicus gilviventris,...,NaN,NaN,CC_BY_4_0,NaN,obsr284567,NaN,NaN,2024-04-17T09:06:42.352Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...
3,964226612,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD_NZ:OBS209588518,Animalia,Chordata,Aves,Passeriformes,Acanthisittidae,Xenicus,Xenicus gilviventris,...,NaN,NaN,CC_BY_4_0,NaN,obsr329542,NaN,NaN,2024-04-17T09:11:09.307Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...
4,962468066,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS207823760,Animalia,Chordata,Aves,Passeriformes,Acanthisittidae,Xenicus,Xenicus gilviventris,...,NaN,NaN,CC_BY_4_0,NaN,obsr292802,NaN,NaN,2024-04-17T08:45:03.835Z,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...

In [3]:
df_sw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2477 entries, 0 to 2476
Data columns (total 50 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   gbifID                            2477 non-null   int64
 1   datasetKey                        2477 non-null   object
 2   occurrenceID                      2458 non-null   object
 3   kingdom                           2477 non-null   object
 4   phylum                            2477 non-null   object
 5   class                             2477 non-null   object
 6   order                             2477 non-null   object
 7   family                            2477 non-null   object
 8   genus                             2477 non-null   object
 9   species                           2477 non-null   object
 10  infraspecificEpithet              0 non-null      float64
 11  taxonRank                         2477 non-null   object
 12  scientificName                    2477 non-null   object
 13  verbatimScientificName            2477 non-null   object
 14  verbatimScientificNameAuthorship  5 non-null      object
 15  countryCode                       2477 non-null   object
 16  locality                          2214 non-null   object
 17  stateProvince                     2445 non-null   object
 18  occurrenceStatus                  2477 non-null   object
 19  individualCount                   1186 non-null   float64
 20  publishingOrgKey                  2477 non-null   object
 21  decimalLatitude                   2456 non-null   float64
 22  decimalLongitude                  2456 non-null   float64
 23  coordinateUncertaintyInMeters     255 non-null    float64
 24  coordinatePrecision               0 non-null      float64
 25  elevation                         0 non-null      float64
 26  elevationAccuracy                 0 non-null      float64
 27  depth                             0 non-null      float64
 28  depthAccuracy                     0 non-null      float64
 29  eventDate                         2474 non-null   object
 30  day                               2457 non-null   float64
 31  month                             2473 non-null   float64
 32  year                              2474 non-null   float64
 33  taxonKey                          2477 non-null   int64
 34  speciesKey                        2477 non-null   int64
 35  basisOfRecord                     2477 non-null   object
 36  institutionCode                   2452 non-null   object
 37  collectionCode                    2458 non-null   object
 38  catalogNumber                     2458 non-null   object
 39  recordNumber                      0 non-null      float64
 40  identifiedBy                      259 non-null    object
 41  dateIdentified                    257 non-null    object
 42  license                           2477 non-null   object
 43  rightsHolder                      283 non-null    object
 44  recordedBy                        2473 non-null   object
 45  typeStatus                        0 non-null      float64
 46  establishmentMeans                19 non-null     object
 47  lastInterpreted                   2477 non-null   object
 48  mediaType                         255 non-null    object
 49  issue                             2461 non-null   object
dtypes: float64(15), int64(3), object(32)
memory usage: 967.7+ KB

In [6]:
df_sw_time_1 = df_sw[df_sw['year'] == 2012.0]

gpd_df_sw_time_1 = (
    gpd.GeoDataFrame(
        df_sw_time_1, geometry=gpd.points_from_xy(df_sw_time_1.decimalLongitude, df_sw_time_1.decimalLatitude), crs="EPSG:4326"
    )
)

# gpd_df_sw_time_1.explore()

In [7]:
df_sw_time_2 = df_sw[df_sw['year'] == 2022.0]

gpd_df_sw_time_2 = (
    gpd.GeoDataFrame(
        df_sw_time_2, geometry=gpd.points_from_xy(df_sw_time_2.decimalLongitude, df_sw_time_2.decimalLatitude), crs="EPSG:4326"
    )
)

# gpd_df_sw_time_2.explore()

In [9]:
df_sw['countryCode'].nunique()

1